[package]
name = "arb-scanner"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = "2.0"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
rand = "0.8"
dashmap = "6.1.0"
parking_lot = "0.12.4"
chrono = "0.4.41"
futures = "0.3.31"

[profile.release]
strip = false
